### ISSUE TITLE
Nested Transactions

### ISSUE THREAD

**Issue by boekkooi** [thephpleague/tactician-doctrine#11]
So I was using the doctrine transaction middleware with the dbal connection configured with `use_savepoints: true` and without the locking middleware. 
This allowed the middleware to begin multiple transactions (and savepoints) and that worked great. Expect when a exception was throw, because the middleware closes the entity manager without checking if it is still in a transaction (`Doctrine\ORM\ORMException: The EntityManager is closed.`).

How would others feel about moving the `$this->entityManager->close()` below the rollback and surrounding it with `if (!$this->entityManager->getConnection()->isTransactionActive() || $this->entityManager->getConnection()->isRollbackOnly()) {`?

**Comment by rosstuck** [comment]
Sounds legit to me, seems like a good idea to respect the nesting limit, especially without the locking middleware (which I have mixed feelings about). If we feel confident those are the only scenarios or the best check possible, I'd say go for it. :)
