### ISSUE TITLE
Handling Domain Events

### ISSUE THREAD

**Issue by borNfreee** [thephpleague/tactician-doctrine#15]
Hello,

are you interested in adding something similar to http://simplebus.github.io/DoctrineORMBridge/doc/domain_events.html to handle the Domain Events?

It would be very useful and I can help with the implementation, but would like to here is it something you want to have in the Tactician or not.

Thank you.

**Comment by rosstuck** [comment]
Hi @borNfreee, thanks for making an issue and asking about this. :) I've used a similar design before and it's pretty handy. 

However, Tactician and SimpleBus have a slightly different philosophy in that SimpleBus does Events and Commands (i.e. messaging), whereas Tactician considers these separate concerns (and probably separate libraries).

So, while this would be neat to have, I probably won't take anything event related into core or a League package. That said, there's certainly a demand for it so if you'd like to maintain it as a 3rd party package, that would be awesome and I'd be happy to link it up from the docs. Does that sound alright? :)

**Comment by borNfreee** [comment]
No problem, thank you for your answer!

Yes, having a 3rd party package is also a great plan, will do it and post a link to you!
