### ISSUE TITLE
Question: why transactional() is not used

### ISSUE THREAD

**Issue by simPod** [thephpleague/tactician-doctrine#23]
I have been looking at https://github.com/thephpleague/tactician-doctrine/blob/master/src/ORM/TransactionMiddleware.php and wondering, why the transaction is handled manually there. Personally I'd choose to use `->transactional()` instead of `->beginTransaction()`. Is there any particular reason or is it just a matter of personal preference? Thanks!

**Comment by rosstuck** [comment]
Hi @simPod, this was previously discussed here: https://github.com/thephpleague/tactician-doctrine/issues/6

tl;dr Transactional messes with return values. If you have any other questions, feel free to reopen this ticket. :)

**Comment by simPod** [comment]
I see. But since that problem is fixed that custom transaction handling code in TransactionMiddleware is no longer necessary, am I right?

(https://github.com/doctrine/orm/blob/1dbacec0e4e1e9264d552441d9888b49a115b806/lib/Doctrine/ORM/EntityManager.php#L238 vs https://github.com/doctrine/orm/blob/0c2ccec9151fd0b44a60f9cc149e2a107d380799/lib/Doctrine/ORM/EntityManager.php#L241)

**Comment by rosstuck** [comment]
Sure, then it's a question of version support. 

Getting it shorter would be cool and will definitely do it when Doctrine 3.0 rolls around but sans a PR with changes and tests, not really too worried about it in the meantime.

**Comment by simPod** [comment]
Kk, thanks for answers!
