### ISSUE TITLE
Composer cannot install tactician-doctrine along with tactician-bundle

### ISSUE THREAD

**Issue by asprega** [thephpleague/tactician-doctrine#5]
Hi. This is an excerpt of my composer.json file:
```
        "league/tactician-bundle":             "v0.1.0",
        "league/tactician-doctrine":           "v0.4.0"
```

When trying to run composer install I get the following error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - league/tactician-bundle v0.1.0 requires league/tactician ^0.5 -> satisfiable by league/tactician[v0.5.0].
    - league/tactician-bundle v0.1.0 requires league/tactician ^0.5 -> satisfiable by league/tactician[v0.5.0].
    - Can only install one of: league/tactician[v0.3.0, v0.5.0].
    - Can only install one of: league/tactician[v0.5.0, v0.3.0].
    - league/tactician-doctrine v0.4.0 requires league/tactician ^0.3 -> satisfiable by league/tactician[v0.3.0].
    - Installation request for league/tactician-doctrine v0.4.0 -> satisfiable by league/tactician-doctrine[v0.4.0].
    - Installation request for league/tactician-bundle v0.1.0 -> satisfiable by league/tactician-bundle[v0.1.0]. 
```

I looked at https://github.com/thephpleague/tactician-command-events/issues/11, and I'd like to ask if you think it's safe to move the requirement to ^0.5. For now my workaround was to install version 0.2.0 of tactician-doctrine.

**Comment by rosstuck** [comment]
Hmm, I think it's probably time to tag another release in general and go through to update everything. I'll try to get on it this weekend to resolve this. Sorry for the difficulty! :sweat:

**Comment by asprega** [comment]
No problem! Thanks for replying.

**Comment by rosstuck** [comment]
@asprega I've just tagged a new release that should resolve this issue, there was an open PR I'd forgotten to merge when we dropped the Command interfaces and that's why this package lagged behind. My apologies for the goof again and if you've got any other issues or ideas, please let me know. :smile:
